var famousPerson = 'Joel Embiid';
console.log(famousPerson);
var isActive = true;
famousPerson = 'Ben Simmons';
console.log(famousPerson);
var num3 = 3;
var num9 = 9;
var sum = num3 + num9;
var animals = ['Cat','Dog','Horse'];
animals.shift();
famousPerson.length;
